export const SELECTED_IMAGE = "SELECTED_IMAGE";
export const CLEAR_SELECTED_IMAGE = "CLEAR_SELECTED_IMAGE";
export const SEND_MAIL_START = "SEND_MAIL_START";
export const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS";
export const SEND_MAIL_ERROR = "SEND_MAIL_ERROR";
export const CLEAR_MAIL_REDUCER = "CLEAR_MAIL_REDUCER"